import { Header } from 'components/Header'
import { Footer } from 'components/Footer'
import { ThemeProvider } from 'next-themes'
import '../../node_modules/typedcssx/dist/core/styles/global.css'
import 'syntax/_syntax.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          <Header />

          {children}

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
